name: Terraform Apply - Generate Prometheus config

on:
  workflow_dispatch: {}
  push:
    branches: [ 'master' ]
    paths:
      - 'main.tf'
      - 'outputs.tf'
      - 'monitoring/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload generated prometheus.yml
        uses: actions/upload-artifact@v4
        with:
          name: prometheus-config
          path: monitoring/prometheus.yml

      # Optional: Commit the generated file back to the repo (disabled by default)
      - name: Commit generated prometheus.yml (optional)
        if: github.event_name == 'workflow_dispatch' && env.COMMIT_GENERATED == 'true'
        env:
          COMMIT_GENERATED: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add monitoring/prometheus.yml
          git commit -m "chore: update prometheus.yml (generated by Terraform)" || echo "no changes to commit"
          git push
